version: '3'

services:
  db:
    build:
      context: ./docker
      dockerfile: postgres.docker
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: web
      POSTGRES_DB: payment
    ports:
      - "54320:5432"